Footer Created
NJACKWinterOfCode/Ravenous pull request #13
Opened 2019-12-09 16:37 UTC by ankingcodes

Resolves #3 
Designed a footer content with social handles & also with list of contributors.
- Added instagram, facebook, youtube and github. Only github icon redirects to github page.
- Added an `anchor` element which redirects to list of contributors on github
note : The icons are animated.
This is how it looks
![Capture](https://user-images.githubusercontent.com/40923324/70454328-40266800-1ad0-11ea-8b0c-7da48fa59f26.PNG)

2019-12-09 16:38 UTC, ankingcodes commented
@rajat2502 please review and let me know for any changes 👍

2019-12-10 09:48 UTC, rajat2502 commented
Remove all links except the GitHub contributors list link.
Also, add the link to the main repo.
Style the footer, Keep it dark grey maybe

2019-12-10 09:51 UTC, ankingcodes commented
@rajat2502 link to main repo is done by clicking the github icon

2019-12-11 11:06 UTC, ankingcodes commented
@rajat2502 I think it looks really good now 👍 
![Revenous-GoogleChrome2019-12-111](https://user-images.githubusercontent.com/40923324/70616361-42a1d280-1c34-11ea-83d4-369c3187bb79.gif)

2019-12-11 17:37 UTC, rajat2502 requested changes

2019-12-11 17:37 UTC, rajat2502 commented on src/components/Footer/Footer.js
> +import "./style.css";
No need of importing style.css again as it is already imported in the App component

2019-12-11 17:37 UTC, rajat2502 commented on src/components/Footer/SocialFollow.js
> +      <br></br>
write it as <br /> instead of a closing tag

2019-12-11 17:38 UTC, rajat2502 commented on src/components/Footer/SocialFollow.js
> +      <br></br>
Also, remove the love icon from the footer

2019-12-19 15:23 UTC, rajat2502 commented
I don't see any updates.
Closing it.

2019-12-19 15:23 UTC, closed without merging

2019-12-20 08:48 UTC, ankingcodes commented
@rajat2502 sorry for delay. Don't you think this footer is better compared to the one that has been implemented? If you'd like I can make the changes now, Let me know about this.